### ISSUE TITLE
Big Block Lettering in Console

### ISSUE THREAD

**Issue by kimpro82** [kimpro82/MyPractice#266]
- Language : Not decided
- Datafile type : YML
- References
  - https://code.sololearn.com/cMjHm80zOip1
  - https://github.com/dominikwilkowski/cfonts

**Comment by kimpro82** [comment]
### by *ChatGPT*

```yml
A:
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#.....#."
B:
  - "######.."
  - "#.....#."
  - "#.....#."
  - "######.."
  - "#.....#."
  - "#.....#."
  - "######.."
```

알파벳 문자들이 위와 같은 형식으로 저장된 `alphabet.yml` 파일을 타입스크립트에서 불러와서 적절한 데이터 타입의 변수로 사용하기 위해서는 YAML 파서를 사용해야 합니다. YAML 파일을 파싱하여 해당 데이터를 자바스크립트 객체로 변환할 수 있습니다.

타입스크립트에서 YAML 파일을 처리하기 위한 라이브러리 중 하나인 `js-yaml`을 사용하여 YAML 파일을 파싱할 수 있습니다. 먼저 `js-yaml` 라이브러리를 설치해야 합니다. 프로젝트 디렉토리에서 다음 명령을 실행하여 `js-yaml`을 설치합니다:

```shell
npm install js-yaml
```

설치가 완료되면, 타입스크립트 파일에서 다음과 같이 `js-yaml`을 사용하여 YAML 파일을 파싱하고 변수로 저장할 수 있습니다:

```ts
import * as fs from 'fs';
import * as yaml from 'js-yaml';

interface Alphabet {
  [key: string]: string[];
}

// YAML 파일 불러오기
const fileContents = fs.readFileSync('alphabet.yml', 'utf8');

// YAML 파싱
const alphabetData: Alphabet = yaml.load(fileContents);

// 사용 예시: A 출력
console.log(alphabetData['A']);
```

위의 코드는 `alphabet.yml` 파일을 불러와서 `Alphabet`이라는 인터페이스에 맞게 데이터를 파싱한 후, `alphabetData` 변수에 저장합니다. `alphabetData` 변수는 알파벳 문자를 키로 갖고, 해당 알파벳의 배열 형태로 저장된 데이터를 가지고 있습니다. `console.log(alphabetData['A'])`를 실행하면 'A'에 해당하는 배열이 출력됩니다.

이 방법을 통해 `alphabet.yml` 파일을 타입스크립트에서 적절한 데이터 타입의 변수로 불러와서 사용할 수 있습니다.

**Comment by kimpro82** [comment]
### by *ChatGPT*

알파벳 'A'부터 'Z'까지의 데이터를 YAML 형식에 맞게 작성해 드리겠습니다:

```yml
A:
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#.....#."
B:
  - "######.."
  - "#.....#."
  - "#.....#."
  - "######.."
  - "#.....#."
  - "#.....#."
  - "######.."
C:
  - "#######."
  - "#......."""
  - "#......."
  - "#......."
  - "#......."
  - "#......."
  - "#######."
D:
  - "######.."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "######.."
E:
  - "#######."
  - "#......."
  - "#......."
  - "######.."
  - "#......."
  - "#......."
  - "#######."
F:
  - "#######."
  - "#......."
  - "#......."
  - "######.."
  - "#......."
  - "#......."
  - "#......."
G:
  - "#######."
  - "#......."
  - "#......."
  - "#..#####"
  - "#.....#."
  - "#.....#."
  - "#######."
H:
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#.....#."
I:
  - "#######."
  - "...#...."
  - "...#...."
  - "...#...."
  - "...#...."
  - "...#...."
  - "#######."
J:
  - "......##"
  - ".......#"
  - ".......#"
  - ".......#"
  - ".......#"
  - "#......#"
  - "#######."
K:
  - "#......."
  - "#......#"
  - "#.....#."
  - "######.."
  - "#.....#."
  - "#......#"
  - "#......."""
L:
  - "#......."
  - "#......."
  - "#......."
  - "#......."
  - "#......."
  - "#......."
  - "#######."
M:
  - "#.....#."
  - "##...##."
  - "#.#.#.#."
  - "#..#..#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
N:
  - "#.....#."
  - "##....#."
  - "#.#...#."
  - "#..#..#."
  - "#...#.#."
  - "#....##."
  - "#.....#."
O:
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#######."
P:
  - "######.."
  - "#.....#."
  - "#.....#."
  - "######.."
  - "#......."
  - "#......."
  - "#......."
Q:
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#..#..#."
  - "#...#.#."
  - "#....##."
  - "#######."
R:
  - "######.."
  - "#.....#."
  - "#.....#."
  - "######.."
  - "#.....#."
  - "#.....#."
  - "#.....#."
S:
  - ".######."
  - "#......."""
  - "#......."""
  - ".######."
  - ".......#"
  - ".......#"
  - "######.."
T:
  - "#######."
  - "...#...."
  - "...#...."
  - "...#...."
  - "...#...."
  - "...#...."
  - "...#...."
U:
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#######."
V:
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - ".#...#.."
  - "..#.#..."
  - "...#...."
  - "...#...."
W:
  - "#.....#."
  - "#.....#."
  - "#..#..#."
  - "#.#.#.#."
  - "##...##."
  - "#.....#."
  - "#.....#."
X:
  - "#.....#."
  - ".#...#.."
  - "..#.#..."
  - "...#...."
  - "..#.#..."
  - ".#...#.."
  - "#.....#."
Y:
  - "#.....#."
  - ".#...#.."
  - "..#.#..."
  - "...#...."
  - "...#...."
  - "...#...."
  - "...#...."
Z:
  - "#######."
  - ".....#.."
  - "....#..."
  - "...#...."
  - "..#....."
  - ".#......"
  - "#######."
```
