### ISSUE TITLE
TypeScript : Big Block Lettering in Console 2

### ISSUE THREAD

**Issue by kimpro82** [kimpro82/MyPractice#268]
## Future Improvements
  - Add lower cases, numbers and space

**Comment by kimpro82** [comment]
## by *ChatGPT*

```yaml
A:
  - "#######."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - "#######."
  - "#.....#."
  - "#.....#."
  - "........"
  - "........"
  - "........"
a:
  - "........"
  - "........"
  - "........"
  - "........"
  - ".#####.."
  - "#.....#."
  - "#.....#."
  - "#.....#."
  - ".#####.."
  - "........"
```

He was still a rookie.
